### ISSUE TITLE
A gradle-wrapper.jar was missing

### ISSUE THREAD

**Issue by rapkin** [gAmUssA/websockets-demos#4]
If I try to enter the following command (in websockets-java-client):

```
./gradlew build
```

I get the following error:

```
Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain
```

**Comment by gAmUssA** [comment]
Hello,  Apparently, jar files were added to .gitignore file.  You you have gradle installed you can run gradle wrap (it should recreate wrapper). After that you can use wrapper commands.  Thanks  

---WBR,Viktor

On February 26, 2015 at 12:10:42 EST, Mikola Parfenyuck notifications@github.com wrote:If I try to enter the following command:  ./gradlew build    I get the following error:  Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain    —Reply to this email directly or view it on GitHub.

**Comment by rapkin** [comment]
After `gradle wrapper` all working fine, thanks a lot.
